name: curtail
base: core22
adopt-info: curtail
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

slots:
  curtail:
    interface: dbus
    bus: session
    name: com.github.huluti.Curtail

apps:
  curtail:
    command: usr/bin/curtail
    extensions: [gnome]
    environment:
      PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - home
      - network
      - network-bind
      - network-status
      - removable-media
      - unity7
    common-id: com.github.huluti.Curtail
    desktop: usr/share/applications/com.github.huluti.Curtail.desktop

parts:
  curtail:
    source: https://github.com/Huluti/Curtail.git
    source-tag: 1.9.1
    source-depth: 1
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.huluti.Curtail.appdata.xml]
    meson-parameters:
      - --prefix=/snap/curtail/current/usr
      - --buildtype=release
    override-pull: |
      craftctl default
      sed -e 's|Icon=com.github.huluti.Curtail|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/com.github.huluti.Curtail.svg|' -i data/com.github.huluti.Curtail.desktop.in
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/curtail/current/usr/bin/curtail
    organize:
      snap/curtail/current/usr: usr

  oxipng:
    source: https://github.com/shssoichiro/oxipng.git
    source-tag: 'v9.1.0'
    source-depth: 1
# ext:updatesnap
#   version-format:
#     lower-than: '46'
#     no-9x-revisions: true    
    after: [curtail]
    plugin: rust
    build-packages:
      - cargo

  deps:
    after: [oxipng]
    plugin: nil
    stage-packages:
      - pngquant
      - scour
      - jpegoptim
    prime:
      - usr/lib/*/libimagequant*
      - usr/lib/python3
      - usr/bin/dh_scour
      - usr/bin/jpegoptim
      - usr/bin/scour
      - usr/bin/pngquant
